### ISSUE TITLE
Should we translate OpenTelemetry term to Japanese or leave English?

### ISSUE THREAD

**Issue by shirou** [open-telemetry/docs-ja#33]
今挙げてるPR #32 で勝手に

- OpenTelemetry用語は英語のままとする

としちゃいましたが、ここは議論すべきところかなと思っています。

1. 英語のママとする
 - pros: OpenTelemetry用語だと分かる。訳語を考える手間がない。読者が他の未訳文書を読んだときに理解が早くなる
 - cons: 日本語として見た場合に違和感がある

2. 日本語に訳す
  - pros: 日本語の文章として一体感が出る
  - cons: 訳語を考える手間が必要。

ご意見をお願いしたいです。

**Comment by ymotongpoo** [comment]
@shirou ありがとうございます。ガイドラインは大元のREADMEにまとめようと思っていたので助かります。

OpenTelmetry用語の翻訳ですが、個人的にはカナカナ語でも訳語が当てられるならそのほうがいいかなと思います。手間はかかりますが、そもそもが翻訳プロジェクトなのでわかりやすく伝えるというのは意味があることだと思っています。

一方で辞書でOpenTelemetry用語とされているTraceやSpanなどといった用語は、より広く他のプロジェクトでも使われているので、様々な事例を集めて検討する必要があると感じています。

**Comment by ymotongpoo** [comment]
一点、英語をそのままで使用する場合は大文字始まりに統一するのが良いと思いました。

**Comment by shirou** [comment]
英語ママ、大文字始まりに統一することにします
