### ISSUE TITLE
Broken links in README.md

### ISSUE THREAD

**Issue by johtani** [open-telemetry/docs-ja#67]
- https://www.ipa.go.jp/security/rfc/RFC2119JA.html is Not found. Maybe https://www.nic.ad.jp/ja/tech/ipa/RFC2119JA.html ?
- コントリビューションワークフローの2.の[参考](https://raw.githubusercontent.com/open-telemetry/docs-ja/master/specification/library-guidelines.md)のリンク。Maybe https://raw.githubusercontent.com/open-telemetry/docs-ja/master/specification/specification/library-guidelines.md

**Comment by katzchang** [comment]
修正します！

**Comment by katzchang** [comment]
修正しました。Thank you @johtani
